# Deze workflow genereert pdfs van de wiki paginas

name: Wiki Generation

on:
  release:
    types: [published] # , created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone the Wiki Repository
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: List contents
        run: ls -la

      - name: Install PDF creation tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Convert markdown files to PDF
        run: |
          mkdir -p pdfs
          for file in wiki/*.md; do
            [ -e "$file" ] || continue
            filename=$(basename "$file" .md)
            pandoc "$file" -o "pdfs/${filename}.pdf"
          done

      - name: Zip PDFs
        run: zip -j wiki.zip pdfs/*.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: wiki.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload assets
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: wiki.zip
      #     asset_name: documentatie.zip
      #     asset_content_type: application/zip
