# Deze workflow genereert pdfs van de wiki paginas

name: Wiki Generation

on:
  release:
    types: [published] # created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install PDF generation tooling
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
      
      - name: Convert markdown files to PDF
        run: |
          mkdir -p pdfs
          for file in *.md; do
            [ -e "$file" ] || continue
            filename=$(basename "$file" .md)
            pandoc "$file" -o "pdfs/${filename}.pdf"
          done

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: pdfs/*.pdf
          asset_name: wiki.zip
          asset_content_type: application/pdf
